name: CD

on:
  workflow_run:
    workflows: ["CI"]
    branches: [main, dev]
    types: 
      - completed
      - requested

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:
    # if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Set up Rust
        uses: hecrj/setup-rust-action@v1
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        if: env.AWS_ACCESS_KEY_ID && env.AWS_SECRET_ACCESS_KEY
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-west-2
          #STAGE: prod
        run: |
          npm install
          npx serverless deploy --conceal
        working-directory: serverless-client